src/Entity/OTV.php
<?php

namespace App\Entity;

use App\Repository\OTVRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OTVRepository::class)]
#[ORM\HasLifecycleCallbacks]
class OTV
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $start_Date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $end_Date = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_At = null;

    #[ORM\Column(length: 255)]
    private ?string $mobilePhone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $landlinePhone = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private ?array $data = null;

    #[ORM\ManyToOne(inversedBy: 'oTVs', cascade: ["persist"])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Residents $residents = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pathToFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fileName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $comments = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\ManyToOne(inversedBy: 'otv', cascade: ["persist"])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Address $address = null;

    #[ORM\ManyToOne(inversedBy: 'OTVs', cascade: ["persist"])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Districts $district = null;

    // Ajouter les valeurs par défaut d'une OTV à la création
    #[ORM\PrePersist]
    public function onPrePersist(): void
    {
        if ($this->status === null) {
            $this->status = "pending";
        }

        if ($this->created_At === null) {
            $this->created_At = new \DateTimeImmutable("now");
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_Date;
    }

    public function setStartDate(\DateTimeInterface $start_Date): static
    {
        $this->start_Date = $start_Date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_Date;
    }

    public function setEndDate(\DateTimeInterface $end_Date): static
    {
        $this->end_Date = $end_Date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_At;
    }

    public function setCreatedAt(\DateTimeImmutable $created_At): static
    {
        $this->created_At = $created_At;

        return $this;
    }


    public function getMobilePhone(): ?string
    {
        return $this->mobilePhone;
    }

    public function setMobilePhone(string $mobilePhone): static
    {
        $this->mobilePhone = $mobilePhone;

        return $this;
    }

    public function getLandlinePhone(): ?string
    {
        return $this->landlinePhone;
    }

    public function setLandlinePhone(?string $landlinePhone): static
    {
        $this->landlinePhone = $landlinePhone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getData(): ?array
    {
        return $this->data;
    }

    public function setData(?array $data): static
    {
        $this->data = $data;

        return $this;
    }

    public function getResidents(): ?Residents
    {
        return $this->residents;
    }

    public function setResidents(?Residents $residents): static
    {
        $this->residents = $residents;

        return $this;
    }

    public function getPathToFile(): ?string
    {
        return $this->pathToFile;
    }

    public function setPathToFile(string $pathToFile): static
    {
        $this->pathToFile = $pathToFile;

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    public function setFileName(string $fileName): static
    {
        $this->fileName = $fileName;

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(?string $comments): static
    {
        $this->comments = $comments;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getDistrict(): ?Districts
    {
        return $this->district;
    }

    public function setDistrict(?Districts $district): static
    {
        $this->district = $district;

        return $this;
    }
}

src/Controller/OTVController.php
<?php

namespace App\Controller;

use App\Entity\OTV;
use App\Form\OtvType;
use App\DTO\OtvRequest;
use App\Entity\Address;
use App\Entity\Districts;
use App\Entity\Residents;
use App\Mapper\OtvMapper;
use Psr\Log\LoggerInterface;
use App\Mapper\AddressMapper;
use App\Services\FileUploader;
use App\Services\PdfGenerator;
use App\Mapper\ResidentsMapper;
use App\Mapper\OTVRequestMapper;
use App\Repository\OTVRepository;
use App\Services\OTVStatusUpdater;
use App\Repository\AddressRepository;
use App\Security\ApiKeyAuthenticator;
use App\Repository\DistrictsRepository;
use App\Repository\ResidentsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


#[Route('/otv')]
class OTVController extends AbstractController
{
    private $uploadsDirectory;
    private $apiKeyAuthenticator;
    private Security $security;
    private OTVStatusUpdater $otvStatusUpdater;
    private LoggerInterface $logger;

    public function __construct(
        Security $security,
        string $uploadsDirectory,
        ApiKeyAuthenticator $apiKeyAuthenticator,
        OTVStatusUpdater $otvStatusUpdater,
        LoggerInterface $logger
    ) {
        $this->uploadsDirectory = $uploadsDirectory;
        $this->apiKeyAuthenticator = $apiKeyAuthenticator;
        $this->security = $security;
        $this->otvStatusUpdater = $otvStatusUpdater;
        $this->logger = $logger;
    }

    #[Route('/', name: 'app_otv_index', methods: ['GET'])]
    public function index(OTVRepository $oTVRepository, DistrictsRepository $districtsRepository): Response
    {

        $currentUser = $this->security->getUser();
        // Vérifier si l'utilisateur est bien connecté
        if (!$currentUser) {
            $this->addFlash('error',  "Vous devez être connecté pour accéder à cette page");
            return $this->redirectToRoute('app_login');
        }

        $OTVs = $oTVRepository->findAll();
        $districts = $districtsRepository->findAll();

        // Mettre à jour le statut de tous les OTVs à l'affichage de l'index
        foreach ($OTVs as $otv) {
            $this->otvStatusUpdater->updateStatus($otv);
        }

        return $this->render('otv/index.html.twig', [
            'OTVs' => $OTVs,
            'districts' => $districts,
        ]);
    }


    #[Route('/notice', name: 'app_otv_notice_pdf', methods: ['GET'])]
    public function noticePdf(OTVRepository $oTVRepository, DistrictsRepository $districtsRepository, PdfGenerator $pdfGenerator): Response
    {
        $districts = $districtsRepository->findAll();
        $OTVsByDistrict = [];

        foreach ($districts as $district) {
            $OTVs = $oTVRepository->findBy(['status' => 'ongoing', 'district' => $district]);
            if (!empty($OTVs)) {
                $OTVsByDistrict[$district->getName()] = $OTVs;
            }
        }

        $logoPolice = $pdfGenerator->imageToBase64($this->getParameter('kernel.project_dir') . '/public/assets/images/Logo_Police_Municipale__France_.webp');
        $html = $this->renderView('documents/noticePdf.html.twig', [
            'OTVsByDistrict' => $OTVsByDistrict,
            'logoPolice' => $logoPolice
        ]);


        $pdfContent = $pdfGenerator->generatePdf($html);

        return new Response($pdfContent, 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'inline; filename="avis_de_passage.pdf"',
        ]);
    }


    #[Route('/new', name: 'app_otv_new', methods: ['GET', 'POST'])]
    public function new(
        AddressMapper $addressMapper,
        ResidentsMapper $residentsMapper,
        AddressRepository $addressRepository,
        ResidentsRepository $residentsRepository,
        FileUploader $fileUploader,
        
        Request $request,
        EntityManagerInterface $entityManager,
        OTVRequestMapper $OTVRequestMapper,
        DistrictsRepository $districtsRepository
    ): Response {
        if (!$this->apiKeyAuthenticator->authenticate($request)) {
            $this->logger->info('Unauthorized request');
            return new JsonResponse(['error' => 'Unauthorized'], Response::HTTP_UNAUTHORIZED);
        }

        // Récupérer toutes les données du formulaire
        $formData = $request->request->all();
        $data = $formData['data'];
        $this->logger->info('Data received: ' . json_encode($data));

        // Vérifier si le résident existe déjà
        $existingResident = $residentsRepository->findOneBy([
            'firstname' => $data['firstname'],
            'lastname' => $data['lastname'],
        ]);
        if ($existingResident) {
            // Le résident existe déjà, utilisez-le pour la suite du traitement
            $resident = $existingResident;
        } else {
            // Le résident n'existe pas, créez une nouvelle entité
            $resident = new Residents();
            $resident = $residentsMapper->mapToEntity($resident, $data);
            $this->logger->info('New resident created: ' . json_encode($resident));
        }

        // Vérifier si l'adresse existe déjà
        $existingAddress = $addressRepository->findOneBy([
            'street' => $data['street'],
            'streetNumber' => $data['streetNumber'],
            'additionnalStreetNumber' => $data['additionalStreetNumber'] ?? null,
            'additionalAddressInfo' => $data['additionalAddressInfo'] ?? null,
        ]);
        if ($existingAddress) {
            // L'adresse existe déjà, utilisez-le pour la suite du traitement
            $address = $existingAddress;
        } else {
            // Le résident n'existe pas, créez une nouvelle entité
            $address = new Address();
            $address = $addressMapper->mapToEntity($address, $data);
            $this->logger->info('New address created: ' . json_encode($address));
        }

        // Vérifier si le quartier existe déjà
        $existingDistrict = $districtsRepository->findOneBy([
            'name' => $data['district'],
        ]);
        if ($existingDistrict) {
            $district = $existingDistrict;
        } else {
            $district = new Districts();
            $district = $district->setName($data['district']);
            $this->logger->info('New district created: ' . json_encode($address));
        }

        // Créer l'entité OTV
        $OTV = new OTV();
        $OTV = $OTVRequestMapper->mapToEntity($OTV, $data);
        $OTV->setResidents($resident);
        $OTV->setAddress($address);
        $OTV->setDistrict($district);
        $this->logger->info('New OTV created: ' . json_encode($OTV));

        // Gérer le fichier uploadé
        /** @var UploadedFile $file **/
        $file = $request->files->get('file');
        if ($file) {
            $this->logger->info('File received: ' . $file->getClientOriginalName());
            try {
                $this->logger->info('Starting file upload...');
                $newFilename = $fileUploader->uploadFile($file, $data['lastname'], $data['firstname']);
                $this->logger->info('File upload successful, new filename: ' . $newFilename);
                $OTV->setFileName($newFilename);
                $OTV->setPathToFile($this->uploadsDirectory . '/' . $newFilename);
                $this->logger->info('File path set on OTV');
            } catch (\Exception $e) {
                $this->logger->error('File upload error: ' . $e->getMessage());
                return new JsonResponse(['error' => 'File upload failed: ' . $e->getMessage()], 500);
            }
        } else {
            $this->logger->info('No file received');
        }

        // Persister les entités

        $entityManager->persist($resident);
        $entityManager->persist($address);
        $entityManager->persist($OTV);
        $this->logger->info('Entities persisted');

        // Flush les entités
        try {
            $entityManager->flush();
            $this->logger->info('Entities flushed');
        } catch (\Exception $e) {
            $this->logger->error($e->getMessage());
            return new JsonResponse(['error' => $e->getMessage()], 500);
        }

        // Retourner une réponse OK si tout se passe bien
        return new JsonResponse(['status' => 'OK'], 200);
    }


    #[Route('/{id}', name: 'app_otv_show', methods: ['GET'])]
    public function show(OTV $otv, OTVRepository $OTVRepository): Response
    {

        $currentUser = $this->security->getUser();
        // Vérifier si l'utilisateur est bien connecté
        if (!$currentUser) {
            $this->addFlash('error',  "Vous devez être connecté pour accéder à cette page");
            return $this->redirectToRoute('home');
        }

        return $this->render('otv/show.html.twig', [
            'otv' => $otv,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_otv_edit', methods: ['POST', 'GET'])]
    public function edit(Request $request, OTV $OTV, OtvMapper $OtvMapper, OtvRequest $OtvRequest, EntityManagerInterface $entityManager): Response
    {

        $currentUser = $this->security->getUser();
        // Vérifier si l'utilisateur est bien connecté
        if (!$currentUser) {
            $this->addFlash('error',  "Vous devez être connecté pour accéder à cette page");
            return $this->redirectToRoute('app_login');
        }

        // Créer un objet OtvRequest à partir des données de l'objet OTV
        $OtvRequest = new OtvRequest();
        $OtvMapper->mapToOtvRequest($OTV, $OtvRequest);

        $form = $this->createForm(OtvType::class, $OtvRequest);
        $form->handleRequest($request);

        try {
            if ($form->isSubmitted() && $form->isValid()) {

templates/otv/_delete_form.html.twig
<form method="post" action="{{ path('app_otv_delete', {'id': otv.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer cette OTV ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ otv.id) }}">
    <button class="btn btn-outline-danger">Supprimer</button>
</form>

templates/otv/edit.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('assets/style/otv.css') }}">
{% endblock %}

{% block title %}OTV
{% endblock %}

{% block body %}
			{{ include('_partials/_flashMessages.html.twig') }}
	<div class="showWrapper background">
		<div class="otvCard">
			<h1>OTV #
				{{otv.id}}</h1>

			{{ include('otv/_form.html.twig', {'button_label': 'Sauvegarder'}) }}
		</div>
	</div>
{% endblock %}

templates/otv/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New OTV{% endblock %}

{% block body %}
    <h1>Create new OTV</h1>

    {{ include('otv/_form.html.twig') }}

    <a href="{{ path('app_o_t_v_index') }}">back to list</a>
{% endblock %}

templates/otv/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}OTV
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('assets/style/otv.css') }}">
{% endblock %}

{% block body %}
	<div class="showWrapper background">
		<div class="otvCard">
			<h2 class="otvTitle">Détail de l'OTV #{{ otv.id }}</h2>

			{# section date création #}
			<div class="lign">
				<p class="label">OTV créée le :</p>
				<p>{{ otv.createdAt|date('d-m-Y') }}</p>
			</div>

			{# section info résident #}
			<div class="data-section">
				<h3>Demandeur</h3>
				<div class="lign">
					<p class="label">Nom :</p>
					<p>{{ otv.residents.lastname }}</p>
				</div>
				<div class="lign">
					<p class="label">Prénom :</p>
					<p>{{ otv.residents.firstname }}</p>
				</div>
				<div class="lign">
					<p class="label">Adresse :</p>
					<p>{{ otv.address.street }}</p>
				</div>
				{% if otv.address.additionnalStreetNumber is not empty or otv.address.additionalAddressInfo is not empty %}
					<div class="lign">
						<p class="label">Informations adresse :</p>
						<p>{{ otv.address.additionnalStreetNumber }}
							/
							{{ otv.address.additionalAddressInfo }}</p>
					</div>
				{% endif %}
				<div class="lign">
					<p class="label">Quartier :</p>
					<p>{{ otv.district.name }}</p>
				</div>
				<div class="lign">
					<p class="label">Téléphone(s) :</p>
					<p>
						{{ otv.mobilePhone }}
						{% if  otv.landlinePhone %}
							/
							{{ otv.landlinePhone }}</p>
					{% endif %}
				</div>
				<div class="lign">
					<p class="label">Courriel :</p>
					<p>{{ otv.email }}</p>
				</div>
			</div>

			{# section contacts d'urgence #}
			{% if otv.data["emergencyContact1"]["lastname"] or otv.data["emergencyContact2"]["lastname"] or otv.data["emergencyContact3"]["lastname"]  %}
				<div class="data-section">
					<h3>Personne(s) à contacter en cas d'urgence</h3>
					{% if otv.data["emergencyContact1"]["lastname"] %}
						<div class="lign">
							<p class="label">Personne 1 :</p>
							{% for item in otv.data["emergencyContact1"] %}
								{% if item %}
									<p>{{ item }}</p>
								{% endif %}
							{% endfor %}
						</div>
					{% endif %}
					{% if otv.data["emergencyContact2"]["lastname"] %}
						<div class="lign">
							<p class="label">Personne 2 :</p>
							{% for item in otv.data["emergencyContact2"] %}
								{% if item %}
									<p>{{ item }}</p>
								{% endif %}
							{% endfor %}
						</div>
					{% endif %}
					{% if otv.data["emergencyContact3"]["lastname"] %}
						<div class="lign">
							<p class="label">Personne 3 :</p>
							{% for item in otv.data["emergencyContact3"] %}
								{% if item %}
									<p>{{ item }}</p>
								{% endif %}
							{% endfor %}
						</div>
					{% endif %}
				</div>
			{% endif %}

			{# Section informations #}
			<div class="data-section">
				<h3>Informations</h3>
				<div class="lign">
					<p class="label">Date de début :</p>
					<p>{{ otv.startDate|date('d-m-Y')}}</p>
				</div>
				<div class="lign">
					<p class="label">Date de fin :</p>
					<p>{{ otv.endDate|date('d-m-Y') }}</p>
				</div>
				{% if otv.data["otvInfo"]["houseType"] %}
					<div class="lign">
						<p class="label">Type de logement :</p>
						<p>{{ otv.data.otvInfo.houseType }}</p>
					</div>
				{% endif %}
				{% if otv.data["authorizedPersons"] %}
					<div class="lign">
						<p class="label">Personnes autorisées :</p>
						<p>{{ otv.data.authorizedPersons }}</p>
					</div>
				{% endif %}
				{% if otv.data["car"] %}
					<div class="lign">
						<p class="label">Voiture :</p>
						<p>{{ otv.data.car }}</p>
					</div>
				{% endif %}
					<div class="lign">
						<p class="label">Alarme :</p>
						{% if otv.data["otvInfo"]["hasAlarm"] == true %}
							<p>
								oui
							</p>
						{% else %}
							<p>
								non
							</p>
						{% endif %}
					</div>
				<div class="lign">
					<p class="label">Alarme extérieure :</p>
					{% if otv.data["otvInfo"]["hasAlarmExt"] == true %}
						<p>
							oui
						</p>
					{% else %}
						<p>
							non
						</p>
					{% endif %}
				</div>
				<div class="lign">
					<p class="label">Animal :</p>
					{% if otv.data["otvInfo"]["hasAnimal"] == true %}
						<p>
							oui
						</p>
					{% else %}
						<p>
							non
						</p>
					{% endif %}
				</div>
				<div class="lign">
					<p class="label">Caméra :</p>
					{% if otv.data["otvInfo"]["hasCamera"] == true %}
						<p>
							oui
						</p>
					{% else %}
						<p>
							non
						</p>
					{% endif %}
				</div>
				{% if otv.data["otvInfo"]["blindsSchedule"] %}
					<div class="lign">
						<p class="label">Horaires des volets automatiques :</p>
						<input type="text" id="blindsSchedule" class="editable" value="{{ otv.data.otvInfo.blindsSchedule }}">
					</div>
				{% endif %}
				{% if otv.data["otvInfo"]["lightsSchedule"] %}
					<div class="lign">
						<p class="label">Horaires des éclairages :</p>
						<input type="text" id="lightsSchedule" class="editable" value="{{ otv.data.otvInfo.lightsSchedule }}">
					</div>
				{% endif %}
				{% if otv.data["otvInfo"]["additionalInfo"] %}
					<div class="lign">
						<p class="label">Autres informations :</p>
						<input type="text" id="additionalInfo" class="editable" value="{{ otv.data.otvInfo.additionalInfo }}">
					</div>
				{% endif %}
			</div>

			{# Justificatif de domicile #}
			{% if otv.pathToFile %}
				<div class="data-section">
					<h3>Justificatif de domicile</h3>
					<div class="lign">
						<p class="label">Fichier :</p>
						<p>
							<a class="light links" href="{{ path('app_file', {'id': otv.id}) }}" target="_blank">
								<i class="fa-solid fa-file-pdf"></i>
								Justificatif de domicile
							</a>
						</p>
					</div>
				</div>
			{% endif %}

			{# Commentaires #}
			{% if otv.comments %}
				<div class="data-section">
					<h3>Commentaires</h3>
					<div class="lign">
						<p>{{ otv.comments }}</p>
					</div>
				</div>
			{% endif %}

			{# Actions #}
			<div class="row align-items-center justify-content-around mt-5">
				<div class="col-auto">
					<a class="redirect" href="{{ path('app_otv_index') }}">
						<i class="fa-solid fa-arrow-left"></i>
						Retour aux OTV
					</a>
				</div>
				<div class="col-auto">
					<a class="userBtn btn btn-outline-primary" href="{{ path('app_otv_edit', {'id': otv.id}) }}">
						Modifier l'OTV
					</a>
				</div>
				<div class="col-auto">
					{{ include('otv/_delete_form.html.twig') }}
				</div>
			</div>

		</div>
	</div>


{% endblock %}